## Weekly Twitter, Facebook and Instagram Organic Data

In [132]:
import pandas as pd
import numpy as np
import datetime as dt
from time import strptime

### Twitter

Read in data export from twitter platform, wrangle, and export cleaned csv

In [137]:
# 10/26-11/1
twitter = pd.read_csv('tw_weekly_pull.csv')
print(twitter.info())
twitter.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 40 columns):
Tweet id                        30 non-null float64
Tweet permalink                 30 non-null object
Tweet text                      30 non-null object
time                            30 non-null object
impressions                     30 non-null int64
engagements                     30 non-null int64
engagement rate                 30 non-null float64
retweets                        30 non-null int64
replies                         30 non-null int64
likes                           30 non-null int64
user profile clicks             30 non-null int64
url clicks                      30 non-null int64
hashtag clicks                  30 non-null int64
detail expands                  30 non-null int64
permalink clicks                30 non-null int64
app opens                       30 non-null int64
app installs                    30 non-null int64
follows                         30 non-null int64
email tweet                     30 non-null int64
dial phone                      30 non-null int64
media views                     30 non-null int64
media engagements               30 non-null int64
promoted impressions            30 non-null object
promoted engagements            30 non-null object
promoted engagement rate        30 non-null object
promoted retweets               30 non-null object
promoted replies                30 non-null object
promoted likes                  30 non-null object
promoted user profile clicks    30 non-null object
promoted url clicks             30 non-null object
promoted hashtag clicks         30 non-null object
promoted detail expands         30 non-null object
promoted permalink clicks       30 non-null object
promoted app opens              30 non-null object
promoted app installs           30 non-null object
promoted follows                30 non-null object
promoted email tweet            30 non-null object
promoted dial phone             30 non-null object
promoted media views            30 non-null object
promoted media engagements      30 non-null object
dtypes: float64(2), int64(17), object(21)
memory usage: 9.5+ KB
None

,Tweet id,Tweet permalink,Tweet text,time,impressions,engagements,engagement rate,retweets,replies,likes,...,promoted hashtag clicks,promoted detail expands,promoted permalink clicks,promoted app opens,promoted app installs,promoted follows,promoted email tweet,promoted dial phone,promoted media views,promoted media engagements
0,1.058140e+18,https://twitter.com/guestbooktbs/status/105813...,Encore. @MichaelRapaport #TheGuestBook https:/...,2018-11-01 23:22 +0000,32081,531,0.016552,10,4,40,...,-,-,-,-,-,-,-,-,-,-
1,1.058090e+18,https://twitter.com/guestbooktbs/status/105809...,@michaelcassidy Agreed! #TheGuestBook,2018-11-01 20:19 +0000,39,0,0.000000,0,0,0,...,-,-,-,-,-,-,-,-,-,-
2,1.058030e+18,https://twitter.com/guestbooktbs/status/105802...,Raise your ✋ if Adam’s performance was everyth...,2018-11-01 16:13 +0000,692,64,0.092486,5,2,23,...,-,-,-,-,-,-,-,-,-,-
3,1.057710e+18,https://twitter.com/guestbooktbs/status/105770...,What exactly went down last night on #TheGuest...,2018-10-31 18:57 +0000,708,23,0.032486,2,1,8,...,-,-,-,-,-,-,-,-,-,-
4,1.057570e+18,https://twitter.com/guestbooktbs/status/105757...,Want to leave your mark on #TheGuestBook? Then...,2018-10-31 10:00 +0000,843,69,0.081851,3,3,12,...,-,-,-,-,-,-,-,-,-,-

In [138]:
# filter out unneeded columns
twitter = twitter.filter(['Tweet permalink', 'Tweet text', 'time', 'impressions','promoted impressions', 'engagements',
                          'engagement rate', 'retweets', 'replies', 'likes', 'media views', 'promoted media views','media engagements'])
twitter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
Tweet permalink         30 non-null object
Tweet text              30 non-null object
time                    30 non-null object
impressions             30 non-null int64
promoted impressions    30 non-null object
engagements             30 non-null int64
engagement rate         30 non-null float64
retweets                30 non-null int64
replies                 30 non-null int64
likes                   30 non-null int64
media views             30 non-null int64
promoted media views    30 non-null object
media engagements       30 non-null int64
dtypes: float64(1), int64(7), object(5)
memory usage: 3.1+ KB

In [139]:
#create 'post type' column indicating whether reply or original post
twitter['post type'] = twitter['Tweet text'].map(lambda x: "reply" if x[0] == '@' else "post")

# create 'vis eng' column calculating visible engagements by adding retweets, replies, likes
twitter['vis eng'] = twitter['retweets'] + twitter['replies'] + twitter['likes']

# create 'view Rate' and 'completion rate' columns by dividing media views and engagements by impressions, respectively
twitter['view rate'] = twitter['media views']/twitter['impressions']
twitter['completion rate'] = twitter['media engagements']/twitter['impressions']

# add 'episode' column assigning episode number: first 2 digits = season number, last 2 digits = episode number
twitter['episode'] = '203'

# convert 'date' column to datetime
twitter['time'] = pd.to_datetime(twitter['time'])

# create 'in-show' column - show aired on 10/30 10pm, so tweets between GMT 10/31 1AM - 6AM are "in-show"
twitter['in-show'] = twitter['time'].map(lambda x: "in-show" if x >= pd.to_datetime(['2018-10-31 01:00:00']) and x <= pd.to_datetime(['2018-10-31 06:00:00']) else "not")

# create empty 'Votes' column
twitter['votes'] = np.nan

print(twitter.info())
twitter.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 20 columns):
Tweet permalink         30 non-null object
Tweet text              30 non-null object
time                    30 non-null datetime64[ns]
impressions             30 non-null int64
promoted impressions    30 non-null object
engagements             30 non-null int64
engagement rate         30 non-null float64
retweets                30 non-null int64
replies                 30 non-null int64
likes                   30 non-null int64
media views             30 non-null int64
promoted media views    30 non-null object
media engagements       30 non-null int64
post type               30 non-null object
vis eng                 30 non-null int64
view rate               30 non-null float64
completion rate         30 non-null float64
episode                 30 non-null object
in-show                 30 non-null object
votes                   0 non-null float64
dtypes: datetime64[ns](1), float64(4), int64(8), object(7)
memory usage: 4.8+ KB
None

,Tweet permalink,Tweet text,time,impressions,promoted impressions,engagements,engagement rate,retweets,replies,likes,media views,promoted media views,media engagements,post type,vis eng,view rate,completion rate,episode,in-show,votes
0,https://twitter.com/guestbooktbs/status/105813...,Encore. @MichaelRapaport #TheGuestBook https:/...,2018-11-01 23:22:00,32081,-,531,0.016552,10,4,40,5020,-,437,post,54,0.156479,0.013622,203,not,NaN
1,https://twitter.com/guestbooktbs/status/105809...,@michaelcassidy Agreed! #TheGuestBook,2018-11-01 20:19:00,39,-,0,0.000000,0,0,0,0,-,0,reply,0,0.000000,0.000000,203,not,NaN
2,https://twitter.com/guestbooktbs/status/105802...,Raise your ✋ if Adam’s performance was everyth...,2018-11-01 16:13:00,692,-,64,0.092486,5,2,23,204,-,23,post,30,0.294798,0.033237,203,not,NaN
3,https://twitter.com/guestbooktbs/status/105770...,What exactly went down last night on #TheGuest...,2018-10-31 18:57:00,708,-,23,0.032486,2,1,8,9,-,9,post,11,0.012712,0.012712,203,not,NaN
4,https://twitter.com/guestbooktbs/status/105757...,Want to leave your mark on #TheGuestBook? Then...,2018-10-31 10:00:00,843,-,69,0.081851,3,3,12,0,-,0,post,18,0.000000,0.000000,203,not,NaN

In [141]:
twitter['time'] = twitter['time'].dt.normalize()
print(twitter['time'].dtype)

#Phase = pre-premiere/premiere week/premiere day/continuity/finale/off season
twitter['phase'] = 'continuity'
#twitter['time'].map(lambda x: "premiere day" if x == pd.to_datetime(['2018-10-23 00:00:00']) else "premiere week")

twitter['messaging'] = twitter['Tweet text'].map(lambda x: "Premiere" if 'premiere' in x else "Tuesday" if 'Tues' in x else "Tuesday" if 'Tuesday' in x else "Tomorrow" if 'tomorrow' in x else "Tonight" if 'tonight' in x else "Tonight" if 'TONIGHT' in x else "On Demand" if 'on demand' in x else "TBS App" if 'TBS App' in x else "Evergreen")

twitter

datetime64[ns]

,Tweet permalink,Tweet text,time,impressions,promoted impressions,engagements,engagement rate,retweets,replies,likes,...,media engagements,post type,vis eng,view rate,completion rate,episode,in-show,votes,phase,messaging
0,https://twitter.com/guestbooktbs/status/105813...,Encore. @MichaelRapaport #TheGuestBook https:/...,2018-11-01,32081,-,531,0.016552,10,4,40,...,437,post,54,0.156479,0.013622,203,not,NaN,continuity,Evergreen
1,https://twitter.com/guestbooktbs/status/105809...,@michaelcassidy Agreed! #TheGuestBook,2018-11-01,39,-,0,0.000000,0,0,0,...,0,reply,0,0.000000,0.000000,203,not,NaN,continuity,Evergreen
2,https://twitter.com/guestbooktbs/status/105802...,Raise your ✋ if Adam’s performance was everyth...,2018-11-01,692,-,64,0.092486,5,2,23,...,23,post,30,0.294798,0.033237,203,not,NaN,continuity,Evergreen
3,https://twitter.com/guestbooktbs/status/105770...,What exactly went down last night on #TheGuest...,2018-10-31,708,-,23,0.032486,2,1,8,...,9,post,11,0.012712,0.012712,203,not,NaN,continuity,Evergreen
4,https://twitter.com/guestbooktbs/status/105757...,Want to leave your mark on #TheGuestBook? Then...,2018-10-31,843,-,69,0.081851,3,3,12,...,0,post,18,0.000000,0.000000,203,not,NaN,continuity,Evergreen
5,https://twitter.com/guestbooktbs/status/105746...,"That's all for now, but the party continues ne...",2018-10-31,564,-,57,0.101064,0,0,9,...,35,post,9,0.679078,0.062057,203,in-show,NaN,continuity,Evergreen
6,https://twitter.com/guestbooktbs/status/105746...,The nerve of some people! #TheGuestBook https:...,2018-10-31,615,-,37,0.060163,0,2,9,...,20,post,11,0.258537,0.032520,203,in-show,NaN,continuity,Evergreen
7,https://twitter.com/guestbooktbs/status/105746...,We demand a recount! #TheGuestBook https://t.c...,2018-10-31,459,-,9,0.019608,0,0,4,...,5,post,4,0.200436,0.010893,203,in-show,NaN,continuity,Evergreen
8,https://twitter.com/guestbooktbs/status/105746...,@tracytran Jealous? #TheGuestBook,2018-10-31,47,-,5,0.106383,0,1,0,...,0,reply,1,0.000000,0.000000,203,in-show,NaN,continuity,Evergreen
9,https://twitter.com/guestbooktbs/status/105746...,Leave a 😬 to let @TheMoyWonder know he's not a...,2018-10-31,621,-,46,0.074074,0,2,13,...,13,post,15,0.214171,0.020934,203,in-show,NaN,continuity,Evergreen
10,https://twitter.com/guestbooktbs/status/105746...,"Well, that escalated quickly... #TheGuestBook ...",2018-10-31,517,-,23,0.044487,0,2,9,...,7,post,11,0.177950,0.013540,203,in-show,NaN,continuity,Evergreen
11,https://twitter.com/guestbooktbs/status/105746...,@_Doo_Wop Ballin on a budget. #TheGuestBook,2018-10-31,97,-,4,0.041237,1,0,1,...,0,reply,2,0.000000,0.000000,203,in-show,NaN,continuity,Evergreen
12,https://twitter.com/guestbooktbs/status/105746...,Doesn't anyone knock anymore? #TheGuestBook ht...,2018-10-31,480,-,11,0.022917,0,2,4,...,3,post,6,0.177083,0.006250,203,in-show,NaN,continuity,Evergreen
13,https://twitter.com/guestbooktbs/status/105746...,His brains aren't what win the ladies over. #T...,2018-10-31,429,-,13,0.030303,0,0,5,...,6,post,5,0.128205,0.013986,203,in-show,NaN,continuity,Evergreen
14,https://twitter.com/guestbooktbs/status/105746...,Clark's going to love hearing this story when ...,2018-10-31,550,-,13,0.023636,0,1,7,...,5,post,8,0.169091,0.009091,203,in-show,NaN,continuity,Evergreen
15,https://twitter.com/guestbooktbs/status/105746...,You must be confusing her with Tickles. #TheGu...,2018-10-31,639,-,34,0.053208,1,2,14,...,14,post,17,0.208138,0.021909,203,in-show,NaN,continuity,Evergreen
16,https://twitter.com/guestbooktbs/status/105746...,@_Doo_Wop If it fits! #TheGuestBook,2018-10-31,111,-,4,0.036036,1,1,1,...,0,reply,3,0.000000,0.000000,203,in-show,NaN,continuity,Evergreen
17,https://twitter.com/guestbooktbs/status/105746...,Therapy can be a real shock to the system. #Th...,2018-10-31,536,-,22,0.041045,1,1,8,...,10,post,10,0.192164,0.018657,203,in-show,NaN,continuity,Evergreen
18,https://twitter.com/guestbooktbs/status/105746...,We'll see how long this lasts... #TheGuestBook...,2018-10-31,449,-,7,0.015590,0,0,3,...,4,post,3,0.153675,0.008909,203,in-show,NaN,continuity,Evergreen
19,https://twitter.com/guestbooktbs/status/105745...,Tonight is @MichaelRapaport approved. 👍 Tune i...,2018-10-31,556,-,11,0.019784,1,0,5,...,2,post,6,0.161871,0.003597,203,in-show,NaN,continuity,Evergreen
20,https://twitter.com/guestbooktbs/status/105745...,Adam's counting down the minutes to a new epis...,2018-10-31,2100,-,27,0.012857,1,1,11,...,6,post,13,0.002857,0.002857,203,in-show,NaN,continuity,Evergreen
21,https://twitter.com/guestbooktbs/status/105741...,"When you need a vacation from work, but not yo...",2018-10-30,864,-,46,0.053241,1,0,10,...,30,post,11,0.604167,0.034722,203,not,NaN,continuity,Evergreen
22,https://twitter.com/guestbooktbs/status/105730...,@MichaelRapaport is back for game night. Count...,2018-10-30,4130,466490,74,0.017918,2,18,0,...,36,reply,20,0.134625,0.008717,203,not,NaN,continuity,Tonight
23,https://twitter.com/guestbooktbs/status/105702...,Don’t let the humility fool you. @CarlyJibson ...,2018-10-29,2894,-,61,0.021078,1,0,16,...,32,post,17,0.149965,0.011057,203,not,NaN,continuity,Evergreen
24,https://twitter.com/guestbooktbs/status/105694...,Count on this: @MichaelRapaport is back on a n...,2018-10-29,31976,-,283,0.008850,4,2,34,...,205,post,40,0.145797,0.006411,203,not,NaN,continuity,Tomorrow
25,https://twitter.com/guestbooktbs/status/105657...,A hint: Picasso isn’t the only artist taking t...,2018-10-28,926,-,36,0.038877,2,1,10,...,22,post,13,0.226782,0.023758,203,not,NaN,continuity,Tuesday
26,https://twitter.com/guestbooktbs/status/105592...,Weird drugs &amp; saliva fingers are what we d...,2018-10-26,248,474958,10,0.040323,0,1,0,...,1,post,1,0.056452,0.004032,203,not,NaN,continuity,Evergreen
27,https://twitter.com/guestbooktbs/status/105592...,"Laughter is a drug, too. So get high with us a...",2018-10-26,161,232940,3,0.018634,0,1,0,...,2,post,1,0.105590,0.012422,203,not,NaN,continuity,Evergreen
28,https://twitter.com/guestbooktbs/status/105589...,Adam's back for round 2. Not that anyone's cou...,2018-10-26,65602,-,1441,0.021966,16,9,97,...,1212,post,122,0.198256,0.018475,203,not,NaN,continuity,Tuesday
29,https://twitter.com/guestbooktbs/status/105585...,Something’s not adding up. 🤔 @MichaelRapaport ...,2018-10-26,1474,682555,64,0.043419,2,10,3,...,36,post,15,0.168250,0.024423,203,not,NaN,continuity,Tuesday

In [142]:
#standardize column names i.e. make all lowercase
twitter.columns = map(str.lower, twitter.columns)
twitter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 22 columns):
tweet permalink         30 non-null object
tweet text              30 non-null object
time                    30 non-null datetime64[ns]
impressions             30 non-null int64
promoted impressions    30 non-null object
engagements             30 non-null int64
engagement rate         30 non-null float64
retweets                30 non-null int64
replies                 30 non-null int64
likes                   30 non-null int64
media views             30 non-null int64
promoted media views    30 non-null object
media engagements       30 non-null int64
post type               30 non-null object
vis eng                 30 non-null int64
view rate               30 non-null float64
completion rate         30 non-null float64
episode                 30 non-null object
in-show                 30 non-null object
votes                   0 non-null float64
phase                   30 non-null object
messaging               30 non-null object
dtypes: datetime64[ns](1), float64(4), int64(8), object(9)
memory usage: 5.2+ KB

In [143]:
#reorder columns
twitter = twitter[['post type', 'tweet permalink', 'tweet text', 'episode', 'time', 'in-show', 'impressions','promoted impressions',
                   'engagements', 'engagement rate', 'retweets', 'replies', 'likes', 'votes', 'vis eng',
                   'media views', 'promoted media views', 'media engagements', 'view rate', 'completion rate', 'phase','messaging']]
twitter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 22 columns):
post type               30 non-null object
tweet permalink         30 non-null object
tweet text              30 non-null object
episode                 30 non-null object
time                    30 non-null datetime64[ns]
in-show                 30 non-null object
impressions             30 non-null int64
promoted impressions    30 non-null object
engagements             30 non-null int64
engagement rate         30 non-null float64
retweets                30 non-null int64
replies                 30 non-null int64
likes                   30 non-null int64
votes                   0 non-null float64
vis eng                 30 non-null int64
media views             30 non-null int64
promoted media views    30 non-null object
media engagements       30 non-null int64
view rate               30 non-null float64
completion rate         30 non-null float64
phase                   30 non-null object
messaging               30 non-null object
dtypes: datetime64[ns](1), float64(4), int64(8), object(9)
memory usage: 5.2+ KB

In [144]:
# convert new dataframe to csv "twitter_weekly.csv"
twitter.to_csv('twitter_weekly.csv')

### Nielsen

Read in data export from Nielsen UI, wrangle and write to csv.

In [145]:
# read in file for current week's episode
# air time: 10/30/18 - 10pm ET
nielsen = pd.read_csv('nielsen_weekly_pull.csv')
nielsen.info()
nielsen.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 14 columns):
Social Content Ratings    176 non-null object
Unnamed: 1                174 non-null object
Unnamed: 2                165 non-null object
Unnamed: 3                165 non-null object
Unnamed: 4                165 non-null object
Unnamed: 5                161 non-null object
Unnamed: 6                161 non-null object
Unnamed: 7                159 non-null object
Unnamed: 8                159 non-null object
Unnamed: 9                159 non-null object
Unnamed: 10               159 non-null object
Unnamed: 11               159 non-null object
Unnamed: 12               159 non-null object
Unnamed: 13               91 non-null object
dtypes: object(14)
memory usage: 20.2+ KB

,Social Content Ratings,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,http://scr.nielsensocial.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Copyright 2018 The Nielsen Company. All right...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Network,TBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Program,The Guest Book,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Program Genre Type,Comedy Series,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Season Number,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Episode,Counting Problems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Episode Number,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,EPG Program ID,SH026058900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,EPG Episode ID,EP026058900023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Air Date,10/30/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Airtime Start Time,10:30 PM EDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Duration (Minutes),30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Live/New,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Report Type,Tweets (Verbatims),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Unique Authors,Original Content,Unique Engagers,Total Engagement,Uniques,Interactions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Twitter,55,68,260,423,302,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,Retweets,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
# toss row indices 0-9 into a new dataframe and isolate episode name
episode_details = nielsen.iloc[:13]
episode_details['episode'] = episode_details.iat[6,1] + str('0') + episode_details.iat[8,1]
episode_details['name'] = episode_details.iat[7,1]
episode_details['air date'] = episode_details.iat[11,1]
episode_details['air time'] = episode_details.iat[12,1]
episode_details.drop(episode_details.index[1:],inplace=True)
episode_details = episode_details.loc[:, ['episode','name','air date','air time']]
episode_details

/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/christina.caddel/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

  episode               name  air date      air time
0     203  Counting Problems  10/30/18  10:30 PM EDT

In [147]:
# bring up row index 17 as header and drop row indices 0-16
nielsen.drop(nielsen.index[:17], inplace=True)
nielsen.columns = nielsen.iloc[0]
nielsen = nielsen[1:]
nielsen = nielsen.reset_index(drop = True)
nielsen.head(15)

17,nan,Unique Authors,Original Content,Unique Engagers,Total Engagement,Uniques,Interactions,nan,nan,nan,nan,nan,nan,nan
0,Twitter,55,68,260,423,302,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Retweets,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Replies,41,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Quotes,11,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Likes,221,333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Tweets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,User,User Profile Url,User ID,Followers,Time Sent (Local),Local Date,Time Sent (GMT),Tweet ID,Tweet,Tweet URL,Interaction Type,Tweet Type,Root ID,Root URL
8,MikeMartin1984,https://twitter.com/MikeMartin1984,8.91138E+17,9,08:13:17 PM EDT,10/30/18,2018-10-31T00:13:17Z,1.05743E+18,@guestbooktbs @MichaelRapaport @TBSNetwork Hey...,https://twitter.com/statuses/1057425240219942914,engagement,reply,1.0573E+18,https://twitter.com/statuses/1057301105678393350
9,ctclevelandfan,https://twitter.com/ctclevelandfan,636291017,47,08:13:18 PM EDT,10/30/18,2018-10-31T00:13:18Z,1.05743E+18,@guestbooktbs @MichaelRapaport @TBSNetwork Mic...,https://twitter.com/statuses/1057425242543538178,engagement,reply,1.0573E+18,https://twitter.com/statuses/1057301105678393350
10,germansean,https://twitter.com/germansean,24078557,274,08:14:42 PM EDT,10/30/18,2018-10-31T00:14:42Z,1.05743E+18,@SmittyBarstool cease and desist,https://twitter.com/statuses/1057425596735733760,engagement,quote,1.0573E+18,https://twitter.com/statuses/1057301105678393350
11,realb_sendek,https://twitter.com/realb_sendek,494230455,43,08:18:35 PM EDT,10/30/18,2018-10-31T00:18:35Z,1.05743E+18,@guestbooktbs @MichaelRapaport @TBSNetwork I l...,https://twitter.com/statuses/1057426571252957185,engagement,reply,1.0573E+18,https://twitter.com/statuses/1057301105678393350
12,brandonwojo,https://twitter.com/brandonwojo,35762725,607,08:18:36 PM EDT,10/30/18,2018-10-31T00:18:36Z,1.05743E+18,Hard pass,https://twitter.com/statuses/1057426574700613632,engagement,quote,1.0573E+18,https://twitter.com/statuses/1057301105678393350
13,JoeFielding,https://twitter.com/JoeFielding,33146810,2215,08:24:32 PM EDT,10/30/18,2018-10-31T00:24:32Z,1.05743E+18,RT @guestbooktbs: @MichaelRapaport is back for...,https://twitter.com/statuses/1057428069160386561,engagement,retweet,1.0573E+18,https://twitter.com/statuses/1057301105678393350
14,JoeFielding,https://twitter.com/JoeFielding,33146810,2215,08:24:53 PM EDT,10/30/18,2018-10-31T00:24:53Z,1.05743E+18,@guestbooktbs @MichaelRapaport @TBSNetwork Yes...,https://twitter.com/statuses/1057428155802169344,engagement,reply,1.0573E+18,https://twitter.com/statuses/1057301105678393350

In [148]:
# calculate value for total mentions and add as column
mentions = nielsen.iloc[8:]
nielsen['total mentions'] = mentions['Unique Authors'].count()

nielsen.head()

17,nan,Unique Authors,Original Content,Unique Engagers,Total Engagement,Uniques,Interactions,nan,nan,nan,nan,nan,nan,nan,total mentions
0,Twitter,55,68,260,423,302,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
1,NaN,NaN,Retweets,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
2,NaN,NaN,Replies,41,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
3,NaN,NaN,Quotes,11,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158
4,NaN,NaN,Likes,221,333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158

In [149]:
# keep only relevant columns and drop all rows except first
nielsen = nielsen[['Unique Authors','Original Content','Unique Engagers','Interactions','total mentions']]
nielsen.drop(nielsen.index[1:], inplace=True)
nielsen.head()

17,Unique Authors,Original Content,Unique Engagers,Interactions,total mentions
0,55,68,260,491,158

In [150]:
# rename and reorder columns
nielsen.columns = ['unique users','total social convos','unique authors/engagers','interactions','total mentions']
nielsen['episode'], nielsen['name'], nielsen['air date'], nielsen['air time'] = episode_details['episode'], episode_details['name'], episode_details['air date'], episode_details['air time']
nielsen = nielsen[['episode','name','air date','air time','unique users','total social convos','unique authors/engagers','interactions','total mentions']]
nielsen.head()

,episode,name,air date,air time,unique users,total social convos,unique authors/engagers,interactions,total mentions
0,203,Counting Problems,10/30/18,10:30 PM EDT,55,68,260,491,158

In [151]:
nielsen.to_csv('nielsen_weekly.csv')

### Facebook

Read in data export from Facebook platform, wrangle, and write to csv.

In [152]:
fb = pd.read_csv('fb_weekly_pull.csv')
print(fb.info())
fb.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 52 columns):
Post ID                                                                        11 non-null object
Permalink                                                                      11 non-null object
Post Message                                                                   11 non-null object
Type                                                                           11 non-null object
Countries                                                                      0 non-null float64
Languages                                                                      0 non-null float64
Posted                                                                         11 non-null object
Audience Targeting                                                             11 non-null object
Lifetime Post Total Reach                                                      12 non-null object
Lifetime Post organic reach                                                    12 non-null object
Lifetime Post Paid Reach                                                       12 non-null object
Lifetime Post Total Impressions                                                12 non-null object
Lifetime Post Organic Impressions                                              12 non-null object
Lifetime Post Paid Impressions                                                 12 non-null object
Lifetime Engaged Users                                                         12 non-null object
Lifetime Matched Audience Targeting Consumers on Post                          12 non-null object
Lifetime Matched Audience Targeting Consumptions on Post                       12 non-null object
Lifetime Negative Feedback from Users                                          12 non-null object
Lifetime Negative Feedback                                                     12 non-null object
Lifetime Post Impressions by people who have liked your Page                   12 non-null object
Lifetime Post reach by people who like your Page                               12 non-null object
Lifetime Post Paid Impressions by people who have liked your Page              12 non-null object
Lifetime Paid reach of a post by people who like your Page                     12 non-null object
Lifetime People who have liked your Page and engaged with your post            12 non-null object
Lifetime Organic views to 95%                                                  12 non-null object
Lifetime Organic views to 95%.1                                                12 non-null object
Lifetime Paid views to 95%                                                     12 non-null object
Lifetime Paid views to 95%.1                                                   12 non-null object
Lifetime Organic Video Views                                                   12 non-null object
Lifetime Organic Video Views.1                                                 12 non-null object
Lifetime Paid Video Views                                                      12 non-null object
Lifetime Paid Video Views.1                                                    12 non-null object
Lifetime Average time video viewed                                             12 non-null object
Lifetime Video length                                                          12 non-null object
Lifetime Talking About This (Post) by action type - share                      8 non-null object
Lifetime Talking About This (Post) by action type - like                       11 non-null float64
Lifetime Talking About This (Post) by action type - comment                    9 non-null float64
Lifetime Post Stories by action type - share                                   8 non-null object
Lifetime Post Stories by action type - like                                    11 non-null float64
Lifetime Post Stories by action type - comment                                 9 non-null float64
Lifetime Post Audience Targeting Unique Consumptions by Type - video play      11 non-null object
Lifetime Post Audience Targeting Unique Consumptions by Type - other clicks    11 non-null float64
Lifetime Post Audience Targeting Unique Consumptions by Type - link clicks     4 non-null float64
Lifetime Matched Audience Targeting Consumptions by Type - video play          11 non-null object
Lifetime Matched Audience Targeting Consumptions by Type - other clicks        11 non-null float64
Lifetime Matched Audience Targeting Consumptions by Type - link clicks         4 non-null float64
Lifetime Negative Feedback from Users by Type - hide_clicks                    7 non-null object
Lifetime Negative Feedback from Users by Type - hide_all_clicks                3 non-null float64
Lifetime Negative Feedback from Users by Type - report_spam_clicks             1 non-null float64
Lifetime Negative Feedback by Type - hide_clicks                               7 non-null object
Lifetime Negative Feedback by Type - hide_all_clicks                           3 non-null float64
Lifetime Negative Feedback by Type - report_spam_clicks                        1 non-null float64
dtypes: float64(14), object(38)
memory usage: 5.0+ KB
None

,Post ID,Permalink,Post Message,Type,Countries,Languages,Posted,Audience Targeting,Lifetime Post Total Reach,Lifetime Post organic reach,...,Lifetime Post Audience Targeting Unique Consumptions by Type - link clicks,Lifetime Matched Audience Targeting Consumptions by Type - video play,Lifetime Matched Audience Targeting Consumptions by Type - other clicks,Lifetime Matched Audience Targeting Consumptions by Type - link clicks,Lifetime Negative Feedback from Users by Type - hide_clicks,Lifetime Negative Feedback from Users by Type - hide_all_clicks,Lifetime Negative Feedback from Users by Type - report_spam_clicks,Lifetime Negative Feedback by Type - hide_clicks,Lifetime Negative Feedback by Type - hide_all_clicks,Lifetime Negative Feedback by Type - report_spam_clicks
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lifetime: The number of people who had your Pa...,Lifetime: The number of people who had your Pa...,...,NaN,Lifetime: The number of clicks anywhere in the...,NaN,NaN,Lifetime: The number of times people have give...,NaN,NaN,Lifetime: The number of people who have given ...,NaN,NaN
1,1067035793417549_1986921484762304,https://www.facebook.com/guestbooktbs/posts/19...,Leave a 👏 to give Adam a round of applause.,Video,NaN,NaN,11/1/18 16:18,,2038,2038,...,NaN,23,141.0,NaN,1,NaN,NaN,1,NaN,NaN
2,1067035793417549_1986457664808686,https://www.facebook.com/guestbooktbs/posts/19...,Raise your ✋ if Adam’s performance was everyth...,Video,NaN,NaN,11/1/18 9:11,,2993,2993,...,1.0,43,202.0,1.0,1,NaN,NaN,1,NaN,NaN
3,1067035793417549_337347266829651,https://www.facebook.com/guestbooktbs/videos/3...,Highlights. Games. Cheeseballs. Get caught up ...,Video,NaN,NaN,10/31/18 15:00,,1388,1388,...,1.0,13,18.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN
4,1067035793417549_1982889608498825,https://www.facebook.com/guestbooktbs/posts/19...,Want to leave your mark on The Guest Book? The...,Status,NaN,NaN,10/31/18 3:00,,937,937,...,11.0,NaN,19.0,11.0,1,NaN,NaN,1,NaN,NaN

In [153]:
#drop unwanted rows and columns
fb.drop(fb.index[0], inplace=True)
fb = fb.filter(['Permalink','Posted','Post Message','Type','Lifetime Post organic reach','Lifetime Post Organic Impressions', 'Lifetime Post Paid Impressions','Lifetime Engaged Users','Lifetime Organic Video Views.1','Lifetime Paid Video Views','Lifetime Organic views to 95%.1','Lifetime Paid views to 95%.1','Lifetime Talking About This (Post) by action type - like','Lifetime Talking About This (Post) by action type - comment','Lifetime Talking About This (Post) by action type - share'])
fb = fb.reset_index(drop=True)
fb.head()

,Permalink,Posted,Post Message,Type,Lifetime Post organic reach,Lifetime Post Organic Impressions,Lifetime Post Paid Impressions,Lifetime Engaged Users,Lifetime Organic Video Views.1,Lifetime Paid Video Views,Lifetime Organic views to 95%.1,Lifetime Paid views to 95%.1,Lifetime Talking About This (Post) by action type - like,Lifetime Talking About This (Post) by action type - comment,Lifetime Talking About This (Post) by action type - share
0,https://www.facebook.com/guestbooktbs/posts/19...,11/1/18 16:18,Leave a 👏 to give Adam a round of applause.,Video,2038,2613,0,146,830,0,208,0,34.0,19.0,4
1,https://www.facebook.com/guestbooktbs/posts/19...,11/1/18 9:11,Raise your ✋ if Adam’s performance was everyth...,Video,2993,3919,0,217,1348,0,450,0,59.0,13.0,4
2,https://www.facebook.com/guestbooktbs/videos/3...,10/31/18 15:00,Highlights. Games. Cheeseballs. Get caught up ...,Video,1388,2000,0,33,253,0,5,0,14.0,3.0,NaN
3,https://www.facebook.com/guestbooktbs/posts/19...,10/31/18 3:00,Want to leave your mark on The Guest Book? The...,Status,937,1278,0,35,0,0,0,0,7.0,4.0,2
4,https://www.facebook.com/guestbooktbs/posts/19...,10/30/18 16:34,"When you need a vacation from work, but not yo...",Video,1400,1891,0,60,642,0,119,0,15.0,3.0,NaN

In [154]:
#rename columns
fb.columns = ['link','date posted','message','media type','reach','organic impressions','paid impressions','engagement','organic video views','paid video views','organic video completes','paid video completes','likes','comments','shares']
fb.head()

,link,date posted,message,media type,reach,organic impressions,paid impressions,engagement,organic video views,paid video views,organic video completes,paid video completes,likes,comments,shares
0,https://www.facebook.com/guestbooktbs/posts/19...,11/1/18 16:18,Leave a 👏 to give Adam a round of applause.,Video,2038,2613,0,146,830,0,208,0,34.0,19.0,4
1,https://www.facebook.com/guestbooktbs/posts/19...,11/1/18 9:11,Raise your ✋ if Adam’s performance was everyth...,Video,2993,3919,0,217,1348,0,450,0,59.0,13.0,4
2,https://www.facebook.com/guestbooktbs/videos/3...,10/31/18 15:00,Highlights. Games. Cheeseballs. Get caught up ...,Video,1388,2000,0,33,253,0,5,0,14.0,3.0,NaN
3,https://www.facebook.com/guestbooktbs/posts/19...,10/31/18 3:00,Want to leave your mark on The Guest Book? The...,Status,937,1278,0,35,0,0,0,0,7.0,4.0,2
4,https://www.facebook.com/guestbooktbs/posts/19...,10/30/18 16:34,"When you need a vacation from work, but not yo...",Video,1400,1891,0,60,642,0,119,0,15.0,3.0,NaN

In [155]:
fb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
link                       11 non-null object
date posted                11 non-null object
message                    11 non-null object
media type                 11 non-null object
reach                      11 non-null object
organic impressions        11 non-null object
paid impressions           11 non-null object
engagement                 11 non-null object
organic video views        11 non-null object
paid video views           11 non-null object
organic video completes    11 non-null object
paid video completes       11 non-null object
likes                      11 non-null float64
comments                   9 non-null float64
shares                     7 non-null object
dtypes: float64(2), object(13)
memory usage: 1.4+ KB

In [156]:
fb = fb.fillna(0)

cols = ['likes','comments','shares','reach','organic impressions','paid impressions','engagement','organic video views','paid video views','organic video completes','paid video completes']

for col in cols:
    fb[col] = fb[col].astype(int)
    
fb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
link                       11 non-null object
date posted                11 non-null object
message                    11 non-null object
media type                 11 non-null object
reach                      11 non-null int64
organic impressions        11 non-null int64
paid impressions           11 non-null int64
engagement                 11 non-null int64
organic video views        11 non-null int64
paid video views           11 non-null int64
organic video completes    11 non-null int64
paid video completes       11 non-null int64
likes                      11 non-null int64
comments                   11 non-null int64
shares                     11 non-null int64
dtypes: int64(11), object(4)
memory usage: 1.4+ KB

In [157]:
fb['date posted'] = pd.to_datetime(fb['date posted'])
fb['date posted'] = fb['date posted'].dt.normalize()
print(fb['date posted'].dtype)
fb.head()

datetime64[ns]

,link,date posted,message,media type,reach,organic impressions,paid impressions,engagement,organic video views,paid video views,organic video completes,paid video completes,likes,comments,shares
0,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Leave a 👏 to give Adam a round of applause.,Video,2038,2613,0,146,830,0,208,0,34,19,4
1,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Raise your ✋ if Adam’s performance was everyth...,Video,2993,3919,0,217,1348,0,450,0,59,13,4
2,https://www.facebook.com/guestbooktbs/videos/3...,2018-10-31,Highlights. Games. Cheeseballs. Get caught up ...,Video,1388,2000,0,33,253,0,5,0,14,3,0
3,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-31,Want to leave your mark on The Guest Book? The...,Status,937,1278,0,35,0,0,0,0,7,4,2
4,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-30,"When you need a vacation from work, but not yo...",Video,1400,1891,0,60,642,0,119,0,15,3,0

In [158]:
## Create and add needed columns
fb['vis eng'] = fb['shares'] + fb['likes'] + fb['comments']
fb['PAID'] = 'ORG'
fb['episode'] = '203'
fb['ER'] = fb['engagement']/fb['reach']
fb['VR'] = fb['organic video views']/fb['organic impressions']
fb['CR'] = fb['organic video completes']/fb['organic impressions']

#Phase = pre-premiere/premiere week/premiere day/continuity/finale/off season
fb['phase'] = 'continuity'
#fb['date posted'].map(lambda x: "premiere day" if x == pd.to_datetime(['2018-10-23 00:00:00']) else "premiere week")

fb

,link,date posted,message,media type,reach,organic impressions,paid impressions,engagement,organic video views,paid video views,...,likes,comments,shares,vis eng,PAID,episode,ER,VR,CR,phase
0,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Leave a 👏 to give Adam a round of applause.,Video,2038,2613,0,146,830,0,...,34,19,4,57,ORG,203,0.071639,0.317643,0.079602,continuity
1,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Raise your ✋ if Adam’s performance was everyth...,Video,2993,3919,0,217,1348,0,...,59,13,4,76,ORG,203,0.072503,0.343965,0.114825,continuity
2,https://www.facebook.com/guestbooktbs/videos/3...,2018-10-31,Highlights. Games. Cheeseballs. Get caught up ...,Video,1388,2000,0,33,253,0,...,14,3,0,17,ORG,203,0.023775,0.126500,0.002500,continuity
3,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-31,Want to leave your mark on The Guest Book? The...,Status,937,1278,0,35,0,0,...,7,4,2,13,ORG,203,0.037353,0.000000,0.000000,continuity
4,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-30,"When you need a vacation from work, but not yo...",Video,1400,1891,0,60,642,0,...,15,3,0,18,ORG,203,0.042857,0.339503,0.062930,continuity
5,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-30,Michael Rapaport's back for game night. Count ...,Video,3269,4476,630348,4551,1084,242697,...,241,41,23,305,ORG,203,1.392169,0.242181,0.088919,continuity
6,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-29,Don’t let the humility fool you. Carly Jibson ...,Video,1943,2531,0,83,889,0,...,19,1,0,20,ORG,203,0.042717,0.351245,0.022916,continuity
7,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-29,"If you thought Adam was weird before, just you...",Video,1295,1704,0,36,319,0,...,11,0,2,13,ORG,203,0.027799,0.187207,0.054577,continuity
8,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-28,"We know it looks weird. Trust us, it is. A new...",Video,1626,2113,0,54,647,0,...,9,0,0,9,ORG,203,0.033210,0.306200,0.137246,continuity
9,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-27,Adam's back for round 2. Not that anyone's cou...,Video,1964,2667,0,104,782,0,...,33,3,3,39,ORG,203,0.052953,0.293213,0.044244,continuity
10,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-26,This teaser doesn't add up. 🤔 Michael Rapaport...,Video,8258,10709,649906,15541,2908,275595,...,828,73,72,973,ORG,203,1.881933,0.271547,0.057895,continuity

In [159]:
#create "messaging" column: 
#if message contains "Premiere", "Tues", "Tomorrow", "Tonight", "On Demand", "TBS App", "Evergreen"
#label as: Premieres,Tuesday,Tomorrow,Tonight,On Demand,TBS App, Evergreen
#fb['messaging'] = fb['message'].map(lambda x: "Premieres" if x == '\s*([^!.?]*?premiere[^!.?]*?)' else "Tuesday" if x == '\s*([^!.?]*?Tues[^!.?]*?)' else "Tomorrow" if x == '\s*([^!.?]*?Tomorrow[^!.?]*?)' else "Tonight" if x == '\s*([^!.?]*?Tonight[^!.?]*?)' else "On Demand" if x == '\s*([^!.?]*?On\sDemand[^!.?]*?)' else "TBS App" if x == '\s*([^!.?]*?TBS\sApp[^!.?]*?)' else "Evergreen")
fb['messaging'] = fb['message'].map(lambda x: "Premiere" if 'premiere' in x else "Tuesday" if 'Tues' in x else "Tuesday" if 'Tuesday' in x else "Tomorrow" if 'tomorrow' in x else "Tonight" if 'tonight' in x else "Tonight" if 'TONIGHT' in x else "On Demand" if 'on demand' in x else "TBS App" if 'TBS App' in x else "Evergreen")
fb

,link,date posted,message,media type,reach,organic impressions,paid impressions,engagement,organic video views,paid video views,...,comments,shares,vis eng,PAID,episode,ER,VR,CR,phase,messaging
0,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Leave a 👏 to give Adam a round of applause.,Video,2038,2613,0,146,830,0,...,19,4,57,ORG,203,0.071639,0.317643,0.079602,continuity,Evergreen
1,https://www.facebook.com/guestbooktbs/posts/19...,2018-11-01,Raise your ✋ if Adam’s performance was everyth...,Video,2993,3919,0,217,1348,0,...,13,4,76,ORG,203,0.072503,0.343965,0.114825,continuity,Evergreen
2,https://www.facebook.com/guestbooktbs/videos/3...,2018-10-31,Highlights. Games. Cheeseballs. Get caught up ...,Video,1388,2000,0,33,253,0,...,3,0,17,ORG,203,0.023775,0.126500,0.002500,continuity,Evergreen
3,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-31,Want to leave your mark on The Guest Book? The...,Status,937,1278,0,35,0,0,...,4,2,13,ORG,203,0.037353,0.000000,0.000000,continuity,Evergreen
4,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-30,"When you need a vacation from work, but not yo...",Video,1400,1891,0,60,642,0,...,3,0,18,ORG,203,0.042857,0.339503,0.062930,continuity,Evergreen
5,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-30,Michael Rapaport's back for game night. Count ...,Video,3269,4476,630348,4551,1084,242697,...,41,23,305,ORG,203,1.392169,0.242181,0.088919,continuity,Tonight
6,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-29,Don’t let the humility fool you. Carly Jibson ...,Video,1943,2531,0,83,889,0,...,1,0,20,ORG,203,0.042717,0.351245,0.022916,continuity,Evergreen
7,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-29,"If you thought Adam was weird before, just you...",Video,1295,1704,0,36,319,0,...,0,2,13,ORG,203,0.027799,0.187207,0.054577,continuity,Tomorrow
8,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-28,"We know it looks weird. Trust us, it is. A new...",Video,1626,2113,0,54,647,0,...,0,0,9,ORG,203,0.033210,0.306200,0.137246,continuity,Tuesday
9,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-27,Adam's back for round 2. Not that anyone's cou...,Video,1964,2667,0,104,782,0,...,3,3,39,ORG,203,0.052953,0.293213,0.044244,continuity,Tuesday
10,https://www.facebook.com/guestbooktbs/posts/19...,2018-10-26,This teaser doesn't add up. 🤔 Michael Rapaport...,Video,8258,10709,649906,15541,2908,275595,...,73,72,973,ORG,203,1.881933,0.271547,0.057895,continuity,Tuesday

In [160]:
fb = fb[['date posted','link','message','media type','PAID','episode','reach','organic impressions','paid impressions','engagement','ER','likes','comments','shares','vis eng','organic video views','paid video views','organic video completes','paid video completes','VR','CR','phase','messaging']]
fb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 23 columns):
date posted                11 non-null datetime64[ns]
link                       11 non-null object
message                    11 non-null object
media type                 11 non-null object
PAID                       11 non-null object
episode                    11 non-null object
reach                      11 non-null int64
organic impressions        11 non-null int64
paid impressions           11 non-null int64
engagement                 11 non-null int64
ER                         11 non-null float64
likes                      11 non-null int64
comments                   11 non-null int64
shares                     11 non-null int64
vis eng                    11 non-null int64
organic video views        11 non-null int64
paid video views           11 non-null int64
organic video completes    11 non-null int64
paid video completes       11 non-null int64
VR                         11 non-null float64
CR                         11 non-null float64
phase                      11 non-null object
messaging                  11 non-null object
dtypes: datetime64[ns](1), float64(3), int64(12), object(7)
memory usage: 2.1+ KB

In [161]:
fb.to_csv('fb_weekly.csv')

### IG Organic

Read in data export from Tracer, wrangle, and write to csv.

In [162]:
ig = pd.read_csv('ig_org_weekly_pull.csv')
print(ig.info())
ig.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
Page Name              7 non-null object
Post Created Date      6 non-null object
Post Permalink         6 non-null object
Post Media Type        6 non-null object
Post Caption           6 non-null object
Reach                  6 non-null float64
Impressions            6 non-null float64
Post Comments Count    6 non-null float64
Post Like Count        6 non-null float64
Engagement             6 non-null float64
Video Views            6 non-null float64
dtypes: float64(6), object(5)
memory usage: 784.0+ bytes
None

,Page Name,Post Created Date,Post Permalink,Post Media Type,Post Caption,Reach,Impressions,Post Comments Count,Post Like Count,Engagement,Video Views
0,The Guest Book,10/28/18,https://www.instagram.com/p/Bpe5_ACAozW/,VIDEO,Is there a cure? Adam will try anything to get...,2780.0,3021.0,1.0,49.0,50.0,1806.0
1,The Guest Book,10/29/18,https://www.instagram.com/p/Bphh3pVg9MR/,VIDEO,Count on this: @MichaelRapaport is back on a n...,1917.0,2208.0,3.0,84.0,90.0,948.0
2,The Guest Book,10/29/18,https://www.instagram.com/p/BpiIU0NHmSH/,VIDEO,Don’t let the humility fool you. @CarlyJibson ...,1828.0,2279.0,0.0,115.0,122.0,1126.0
3,The Guest Book,10/31/18,https://www.instagram.com/p/Bpm79psg_68/,IMAGE,What exactly went down last night on The Guest...,764.0,923.0,3.0,50.0,53.0,0.0
4,The Guest Book,10/31/18,https://www.instagram.com/p/BpmzVRYn2Fm/,VIDEO,"When you need a vacation from work, but not yo...",942.0,1113.0,2.0,67.0,69.0,510.0

In [163]:
#drop unwanted columns
ig.drop(columns = ['Page Name'], axis=1, inplace=True)
ig.drop(ig.index[-2:], inplace=True)
ig

,Post Created Date,Post Permalink,Post Media Type,Post Caption,Reach,Impressions,Post Comments Count,Post Like Count,Engagement,Video Views
0,10/28/18,https://www.instagram.com/p/Bpe5_ACAozW/,VIDEO,Is there a cure? Adam will try anything to get...,2780.0,3021.0,1.0,49.0,50.0,1806.0
1,10/29/18,https://www.instagram.com/p/Bphh3pVg9MR/,VIDEO,Count on this: @MichaelRapaport is back on a n...,1917.0,2208.0,3.0,84.0,90.0,948.0
2,10/29/18,https://www.instagram.com/p/BpiIU0NHmSH/,VIDEO,Don’t let the humility fool you. @CarlyJibson ...,1828.0,2279.0,0.0,115.0,122.0,1126.0
3,10/31/18,https://www.instagram.com/p/Bpm79psg_68/,IMAGE,What exactly went down last night on The Guest...,764.0,923.0,3.0,50.0,53.0,0.0
4,10/31/18,https://www.instagram.com/p/BpmzVRYn2Fm/,VIDEO,"When you need a vacation from work, but not yo...",942.0,1113.0,2.0,67.0,69.0,510.0
5,11/1/18,https://www.instagram.com/p/Bpp_orVARuS/,VIDEO,Encore. @MichaelRapaport #TheGuestBook,1018.0,1216.0,4.0,87.0,96.0,451.0

In [164]:
#rename columns
ig.columns = ['date','link','media type','caption','reach','impressions','comments','likes','engagement','video views']

#add columns
ig['episode'] = '203'
ig['vis eng'] = ig['likes'] + ig['comments']
ig['eng rate'] = ig['engagement']/ig['impressions']
ig['view rate'] = ig['video views']/ig['impressions']

ig['date'] = pd.to_datetime(ig['date'])
ig['date'] = ig['date'].dt.normalize()

#Phase = pre-premiere/premiere week/premiere day/continuity/finale/off season
ig['phase'] = 'continuity'
#ig['date'].map(lambda x: "premiere day" if x == pd.to_datetime(['2018-10-23 00:00:00']) else "premiere week")

print(ig.info())
ig.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 15 columns):
date           6 non-null datetime64[ns]
link           6 non-null object
media type     6 non-null object
caption        6 non-null object
reach          6 non-null float64
impressions    6 non-null float64
comments       6 non-null float64
likes          6 non-null float64
engagement     6 non-null float64
video views    6 non-null float64
episode        6 non-null object
vis eng        6 non-null float64
eng rate       6 non-null float64
view rate      6 non-null float64
phase          6 non-null object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 768.0+ bytes
None

,date,link,media type,caption,reach,impressions,comments,likes,engagement,video views,episode,vis eng,eng rate,view rate,phase
0,2018-10-28,https://www.instagram.com/p/Bpe5_ACAozW/,VIDEO,Is there a cure? Adam will try anything to get...,2780.0,3021.0,1.0,49.0,50.0,1806.0,203,50.0,0.016551,0.597815,continuity
1,2018-10-29,https://www.instagram.com/p/Bphh3pVg9MR/,VIDEO,Count on this: @MichaelRapaport is back on a n...,1917.0,2208.0,3.0,84.0,90.0,948.0,203,87.0,0.040761,0.429348,continuity
2,2018-10-29,https://www.instagram.com/p/BpiIU0NHmSH/,VIDEO,Don’t let the humility fool you. @CarlyJibson ...,1828.0,2279.0,0.0,115.0,122.0,1126.0,203,115.0,0.053532,0.494076,continuity
3,2018-10-31,https://www.instagram.com/p/Bpm79psg_68/,IMAGE,What exactly went down last night on The Guest...,764.0,923.0,3.0,50.0,53.0,0.0,203,53.0,0.057421,0.000000,continuity
4,2018-10-31,https://www.instagram.com/p/BpmzVRYn2Fm/,VIDEO,"When you need a vacation from work, but not yo...",942.0,1113.0,2.0,67.0,69.0,510.0,203,69.0,0.061995,0.458221,continuity

In [165]:
#messaging column based on caption containing certain words
ig['messaging'] = ig['caption'].map(lambda x: "Premiere" if 'premiere' in x else "Tuesday" if 'Tues' in x else "Tuesday" if 'Tuesday' in x else "Tomorrow" if 'tomorrow' in x else "Tonight" if 'tonight' in x else "Tonight" if 'TONIGHT' in x else "On Demand" if 'on demand' in x else "TBS App" if 'TBS App' in x else "Evergreen")

print(ig.info())
ig.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 16 columns):
date           6 non-null datetime64[ns]
link           6 non-null object
media type     6 non-null object
caption        6 non-null object
reach          6 non-null float64
impressions    6 non-null float64
comments       6 non-null float64
likes          6 non-null float64
engagement     6 non-null float64
video views    6 non-null float64
episode        6 non-null object
vis eng        6 non-null float64
eng rate       6 non-null float64
view rate      6 non-null float64
phase          6 non-null object
messaging      6 non-null object
dtypes: datetime64[ns](1), float64(9), object(6)
memory usage: 816.0+ bytes
None

,date,link,media type,caption,reach,impressions,comments,likes,engagement,video views,episode,vis eng,eng rate,view rate,phase,messaging
0,2018-10-28,https://www.instagram.com/p/Bpe5_ACAozW/,VIDEO,Is there a cure? Adam will try anything to get...,2780.0,3021.0,1.0,49.0,50.0,1806.0,203,50.0,0.016551,0.597815,continuity,Tuesday
1,2018-10-29,https://www.instagram.com/p/Bphh3pVg9MR/,VIDEO,Count on this: @MichaelRapaport is back on a n...,1917.0,2208.0,3.0,84.0,90.0,948.0,203,87.0,0.040761,0.429348,continuity,Tomorrow
2,2018-10-29,https://www.instagram.com/p/BpiIU0NHmSH/,VIDEO,Don’t let the humility fool you. @CarlyJibson ...,1828.0,2279.0,0.0,115.0,122.0,1126.0,203,115.0,0.053532,0.494076,continuity,Evergreen
3,2018-10-31,https://www.instagram.com/p/Bpm79psg_68/,IMAGE,What exactly went down last night on The Guest...,764.0,923.0,3.0,50.0,53.0,0.0,203,53.0,0.057421,0.000000,continuity,Evergreen
4,2018-10-31,https://www.instagram.com/p/BpmzVRYn2Fm/,VIDEO,"When you need a vacation from work, but not yo...",942.0,1113.0,2.0,67.0,69.0,510.0,203,69.0,0.061995,0.458221,continuity,Evergreen

In [166]:
#reorder columns
ig = ig[['date','link','media type','caption','episode','reach','impressions','engagement','eng rate','likes','comments','vis eng','video views','view rate','phase','messaging']]

ig.head()

,date,link,media type,caption,episode,reach,impressions,engagement,eng rate,likes,comments,vis eng,video views,view rate,phase,messaging
0,2018-10-28,https://www.instagram.com/p/Bpe5_ACAozW/,VIDEO,Is there a cure? Adam will try anything to get...,203,2780.0,3021.0,50.0,0.016551,49.0,1.0,50.0,1806.0,0.597815,continuity,Tuesday
1,2018-10-29,https://www.instagram.com/p/Bphh3pVg9MR/,VIDEO,Count on this: @MichaelRapaport is back on a n...,203,1917.0,2208.0,90.0,0.040761,84.0,3.0,87.0,948.0,0.429348,continuity,Tomorrow
2,2018-10-29,https://www.instagram.com/p/BpiIU0NHmSH/,VIDEO,Don’t let the humility fool you. @CarlyJibson ...,203,1828.0,2279.0,122.0,0.053532,115.0,0.0,115.0,1126.0,0.494076,continuity,Evergreen
3,2018-10-31,https://www.instagram.com/p/Bpm79psg_68/,IMAGE,What exactly went down last night on The Guest...,203,764.0,923.0,53.0,0.057421,50.0,3.0,53.0,0.0,0.000000,continuity,Evergreen
4,2018-10-31,https://www.instagram.com/p/BpmzVRYn2Fm/,VIDEO,"When you need a vacation from work, but not yo...",203,942.0,1113.0,69.0,0.061995,67.0,2.0,69.0,510.0,0.458221,continuity,Evergreen

In [167]:
#write to csv
ig.to_csv('ig_org_weekly.csv')